export enum TeacherSpecialization {
  WEB_FRONTEND = 'WEB_FRONTEND',
  WEB_BACKEND = 'WEB_BACKEND',
  FULLSTACK = 'FULLSTACK',
  MOBILE = 'MOBILE',
  PYTHON = 'PYTHON',
  JAVA = 'JAVA',
  CPLUS = 'CPLUS',
  CYBER_SECURITY = 'CYBER_SECURITY',
  UI_UX = 'UI_UX',
  GRAPHIC_DESIGN = 'GRAPHIC_DESIGN',
  DATA_SCIENCE = 'DATA_SCIENCE',
  SMM = 'SMM',
  GAME_DEV = 'GAME_DEV',
  ROBOTICS = 'ROBOTICS',

  // yangi sohalar
  DEVOPS = 'DEVOPS',
  CLOUD_ENGINEERING = 'CLOUD_ENGINEERING',
  MACHINE_LEARNING = 'MACHINE_LEARNING',
  AI_RESEARCH = 'AI_RESEARCH',
  BLOCKCHAIN = 'BLOCKCHAIN',
  IOT = 'IOT', // Internet of Things
  QA_TESTING = 'QA_TESTING',
  DIGITAL_MARKETING = 'DIGITAL_MARKETING',
  ANIMATION = 'ANIMATION',
  AR_VR_DEV = 'AR_VR_DEV',
}
